export const COPY_REVEAL_TIME = 1.35;
export const COPY_REVEAL_BASE_DURATION = 500;
export const COPY_REVEAL_MIN_DURATION = 150;
export const COPY_REVEAL_STAGGER = 360;
export const COPY_REVEAL_MIN_STAGGER = 180;
export const COPY_FULLY_VISIBLE_HOLD = 500;

export const MASTER_INTRO_END_TIME = 5.041667;
export const MASTER_VIDEO_SRC = "/hero/hero-master-scroll.mp4";
export const MASTER_VIDEO_POSTER_SRC =
  "/hero/service-light-start-16x9-v3.png";
export const INTRO_MAX_PLAYBACK_RATE = 4;
export const SCROLL_VELOCITY_FOR_MAX_SPEED = 2400;

export const ENGINE_VIDEO_START_PROGRESS = 0.18;
export const ENGINE_VIDEO_END_PROGRESS = 0.94;
export const ENGINE_HOOD_OPEN_PROGRESS = 0.985;
export const HERO_COPY_EXIT_START_PROGRESS = 0.13;
export const HERO_COPY_EXIT_DURATION =
  ENGINE_VIDEO_START_PROGRESS - HERO_COPY_EXIT_START_PROGRESS;
export const HERO_NAV_EXIT_START_PROGRESS = 0.145;
export const HERO_NAV_EXIT_DURATION =
  ENGINE_VIDEO_START_PROGRESS - HERO_NAV_EXIT_START_PROGRESS;

export const SCROLLY_TRANSITION_SPEED = 10;
export const SCROLLY_FRAME_THRESHOLD = 1 / 48;
export const ENGINE_VIDEO_READY_TIMEOUT = 10_000;
export const MASTER_VIDEO_MAX_RETRIES = 1;
export const MASTER_VIDEO_RETRY_DELAY = 500;
export const LOCKED_SCROLL_TOLERANCE = 1;

export const HERO_SCROLL_DISTANCE_VH = 280;
export const HOOD_CTA_HOLD_DISTANCE_VH = 100;
export const HOOD_CTA_TRIGGER_VIEWPORT_LINE = 66;
export const HOOD_CTA_REVEAL_AT =
  ENGINE_VIDEO_START_PROGRESS +
  (ENGINE_VIDEO_END_PROGRESS - ENGINE_VIDEO_START_PROGRESS) *
    ENGINE_HOOD_OPEN_PROGRESS;
export const HOOD_CTA_TRIGGER_TOP_VH =
  HOOD_CTA_TRIGGER_VIEWPORT_LINE +
  HERO_SCROLL_DISTANCE_VH * HOOD_CTA_REVEAL_AT;

export const HOOD_CTA_DESCRIPTION =
  "Опишите симптомы — подберём время и скажем, с чего начать.";
